name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions ğŸš€
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸ‰ The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "ğŸ§ This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "ğŸ” The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: echo "ğŸ’¡ The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "ğŸ–¥ï¸ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls -las ${{ github.workspace }}
      - run: echo "ğŸ This job's status is ${{ job.status }}."
  test-codespace:
    runs-on: ubuntu-latest
    env:
      RepositoryName: "codespaces-synchronizer"
      RepoName: "$GITHUB_REPOSITORY"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Test Codespace (devcontainer) build and run multiple commands
        uses: devcontainers/ci@v0.3
        with:
          runCmd: |
            echo "Listing files:"
            ls -la
            echo "Current directory:"
            pwd
            echo "Running script if present:"
            if [ -f main.sh ]; then
              bash main.sh
            elif [ -f main.py ]; then
              python3 main.py
            else
              echo "No main.sh or main.py found."
            fi
  kind-setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up KinD
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.20.0"
          # config: kind.config.yaml # Optional: Uncomment to use a config file
      - name: Run tests
        run: |
          kubectl cluster-info
          kubectl get nodes
